version: '1.0'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpass123!
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postpass123!
    ports:
      - '5000:5000'
    depends_on:
      - 'db'
volumes:
  db:
    driver: local
